### PR TITLE
Update QC summary template

### PR DESCRIPTION
**Pull request by michaelmcd18**

### CODE REVIEW

**Comment by andersone1** [comment]
@michaelmcd18 Include "Days Since Last Rev"

**Comment by andersone1** [comment]
image

**Comment by michaelmcd18** [comment]
Screenshot 2024-06-25 at 10 32 25 AM

@andersone1 A couple updates done to this table, added a `Days since last edit` column. Also now have text wrapping for the `File` column so the table will always stay on the page, regardless of file path length

**Comment by michaelmcd18** [comment]
[example-sum.pdf](https://github.com/user-attachments/files/15973100/example-sum.pdf)

Realizing now I could've just uploaded the new pdf output instead of screenshots

**Comment by seth127** [comment]
@michaelmcd18 drive-by comment: can we put the revision number (i.e. the most recent at the time this summary was cut) at the top of the doc? Probably right under the date stamp, something like "Summary as of revision ___".

Any thoughts on that?

**Pull request closed without merging**
